/**
 * usersApi — RTK Query slice for /api/users
 *
 * The five CRUD endpoints come for free from createCrudApi.
 * Search and login are injected as collection-specific extras.
 *
 * Exported hooks follow RTK Query naming conventions:
 *
 *   useGetUsersQuery()
 *   useGetUserByIdQuery(id)
 *   useCreateUserMutation()
 *   useUpdateUserMutation()
 *   useRemoveUserMutation()
 *   useSearchUsersQuery(q)
 *   useLoginUserMutation()
 */

import { createCrudApi } from './crudApi.factory';

// ─── Types ────────────────────────────────────────────────────────────────────

export interface UserResponse {
  _id: string;
  email: string;
  firstName: string;
  lastName: string;
  role: 'user' | 'admin';
  createdAt: string;
  updatedAt: string;
}

export interface CreateUserDTO {
  email: string;
  password: string;
  firstName: string;
  lastName: string;
}

export interface UpdateUserDTO {
  email?: string;
  firstName?: string;
  lastName?: string;
  role?: 'user' | 'admin';
}

export interface UserLoginDTO {
  email: string;
  password: string;
}

// ─── API slice ────────────────────────────────────────────────────────────────

export const usersApi = createCrudApi<UserResponse, CreateUserDTO, UpdateUserDTO>({
  reducerPath: 'usersApi',
  collectionPath: '/api/users',
  tagType: 'User',

  extraEndpoints: (builder) => ({
    /**
     * GET /api/users/search?q=<term>
     * Partial, case-insensitive match on firstName, lastName, email.
     */
    searchUsers: builder.query<UserResponse[], string>({
      query: (q) => `/api/users/search?q=${encodeURIComponent(q)}`,
      providesTags: [{ type: 'User', id: 'SEARCH' }],
    }),

    /**
     * POST /api/users/login
     * Returns the sanitized user (no passwordHash).
     */
    loginUser: builder.mutation<UserResponse, UserLoginDTO>({
      query: (body) => ({ url: '/api/users/login', method: 'POST', body }),
    }),
  }),
});

// ─── Exported hooks ───────────────────────────────────────────────────────────

export const {
  // CRUD — auto-generated by factory
  useGetAllQuery:    useGetUsersQuery,
  useGetByIdQuery:   useGetUserByIdQuery,
  useCreateMutation: useCreateUserMutation,
  useUpdateMutation: useUpdateUserMutation,
  useRemoveMutation: useRemoveUserMutation,
  // Collection-specific
  useSearchUsersQuery,
  useLoginUserMutation,
} = usersApi;

// ─── Typed convenience wrappers (plain async functions) ───────────────────────
// Use these outside of React components or in thunks where hooks aren't available.

import { store } from '../store/store';

export const getUsers     = ()                                => store.dispatch(usersApi.endpoints.getAll.initiate());
export const getUser      = (id: string)                      => store.dispatch(usersApi.endpoints.getById.initiate(id));
export const createUser   = (data: CreateUserDTO)             => store.dispatch(usersApi.endpoints.create.initiate(data));
export const updateUser   = (id: string, data: UpdateUserDTO) => store.dispatch(usersApi.endpoints.update.initiate({ id, data }));
export const deleteUser   = (id: string)                      => store.dispatch(usersApi.endpoints.remove.initiate(id));
export const searchUsers  = (q: string)                       => store.dispatch(usersApi.endpoints.searchUsers.initiate(q));
