/**
 * UsersExample.tsx
 *
 * Demonstrates every CRUD hook generated by the usersApi slice.
 * This is an example component — adapt it to your actual UI needs.
 *
 * Hooks available:
 *   useGetUsersQuery()          — fetch the full list
 *   useGetUserByIdQuery(id)     — fetch a single user
 *   useCreateUserMutation()     — create a new user
 *   useUpdateUserMutation()     — update an existing user
 *   useRemoveUserMutation()     — delete a user
 *   useSearchUsersQuery(q)      — search users (collection-specific)
 *   useLoginUserMutation()      — login as a user (collection-specific)
 */

import { useState } from 'react';
import {
  useGetUsersQuery,
  useGetUserByIdQuery,
  useCreateUserMutation,
  useUpdateUserMutation,
  useRemoveUserMutation,
  useSearchUsersQuery,
  useLoginUserMutation,
  type CreateUserDTO,
  type UserResponse,
} from '../services/usersApi';

// ─── List all users ──────────────────────────────────────────────────────────

export function UserList() {
  const { data: users, isLoading, isError } = useGetUsersQuery();

  if (isLoading) return <p>Loading users…</p>;
  if (isError)   return <p>Failed to load users.</p>;

  return (
    <ul>
      {users?.map((u) => (
        <li key={u._id}>
          {u.firstName} {u.lastName} — {u.email}
        </li>
      ))}
    </ul>
  );
}

// ─── Fetch a single user by id ───────────────────────────────────────────────

export function UserDetail({ id }: { id: string }) {
  const { data: user, isLoading } = useGetUserByIdQuery(id);

  if (isLoading) return <p>Loading…</p>;
  if (!user)     return <p>User not found.</p>;

  return (
    <div>
      <h2>{user.firstName} {user.lastName}</h2>
      <p>{user.email} — {user.role}</p>
    </div>
  );
}

// ─── Create a user ───────────────────────────────────────────────────────────

export function CreateUserForm() {
  const [createUser, { isLoading }] = useCreateUserMutation();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    const payload: CreateUserDTO = {
      email:     fd.get('email')     as string,
      password:  fd.get('password')  as string,
      firstName: fd.get('firstName') as string,
      lastName:  fd.get('lastName')  as string,
    };
    try {
      const user = await createUser(payload).unwrap();
      console.log('Created:', user);
    } catch (err) {
      console.error('Create failed:', err);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input name="firstName" placeholder="First name" required />
      <input name="lastName"  placeholder="Last name"  required />
      <input name="email"     type="email" placeholder="Email" required />
      <input name="password"  type="password" placeholder="Password" required />
      <button type="submit" disabled={isLoading}>
        {isLoading ? 'Creating…' : 'Create user'}
      </button>
    </form>
  );
}

// ─── Update a user ───────────────────────────────────────────────────────────

export function UpdateUserForm({ user }: { user: UserResponse }) {
  const [updateUser, { isLoading }] = useUpdateUserMutation();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    try {
      const updated = await updateUser({
        id: user._id,
        data: {
          firstName: fd.get('firstName') as string,
          lastName:  fd.get('lastName')  as string,
        },
      }).unwrap();
      console.log('Updated:', updated);
    } catch (err) {
      console.error('Update failed:', err);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input name="firstName" defaultValue={user.firstName} required />
      <input name="lastName"  defaultValue={user.lastName}  required />
      <button type="submit" disabled={isLoading}>
        {isLoading ? 'Saving…' : 'Save changes'}
      </button>
    </form>
  );
}

// ─── Delete a user ───────────────────────────────────────────────────────────

export function DeleteUserButton({ id }: { id: string }) {
  const [removeUser, { isLoading }] = useRemoveUserMutation();

  return (
    <button
      onClick={() => removeUser(id)}
      disabled={isLoading}
    >
      {isLoading ? 'Deleting…' : 'Delete'}
    </button>
  );
}

// ─── Search users (collection-specific) ─────────────────────────────────────

export function UserSearch() {
  const [query, setQuery] = useState('');
  const { data: results, isFetching } = useSearchUsersQuery(query, {
    skip: query.length < 2, // only search after 2+ chars
  });

  return (
    <div>
      <input
        value={query}
        onChange={(e) => setQuery(e.target.value)}
        placeholder="Search users…"
      />
      {isFetching && <span> Searching…</span>}
      <ul>
        {results?.map((u) => (
          <li key={u._id}>{u.firstName} {u.lastName} ({u.email})</li>
        ))}
      </ul>
    </div>
  );
}

// ─── Login (collection-specific) ────────────────────────────────────────────

export function LoginForm() {
  const [loginUser, { isLoading, error }] = useLoginUserMutation();

  const handleSubmit = async (e: React.FormEvent<HTMLFormElement>) => {
    e.preventDefault();
    const fd = new FormData(e.currentTarget);
    try {
      const user = await loginUser({
        email:    fd.get('email')    as string,
        password: fd.get('password') as string,
      }).unwrap();
      console.log('Logged in as:', user);
    } catch (err) {
      console.error('Login failed:', err);
    }
  };

  return (
    <form onSubmit={handleSubmit}>
      <input name="email"    type="email"    placeholder="Email"    required />
      <input name="password" type="password" placeholder="Password" required />
      {error && <p>Login failed — check your credentials.</p>}
      <button type="submit" disabled={isLoading}>
        {isLoading ? 'Logging in…' : 'Log in'}
      </button>
    </form>
  );
}
