import { ThemeColor } from "@inithium/types";

export interface InteractiveColorTokens {
  bg: string;
  bgContrast: string;
  text: string;
  textContrast: string;
  border: string;
  hoverBg: string;
  hoverBgContrast: string;
  hoverText: string;
  hoverTextContrast: string;
  hoverBorderB: string;
}

export const INTERACTIVE_COLOR_MAP: Record<ThemeColor, InteractiveColorTokens> =
  {
    primary: {
      bg: "bg-primary",
      bgContrast: "bg-primary-contrast",
      text: "text-primary",
      textContrast: "text-primary-contrast",
      border: "border-primary",
      hoverBg: "hover:bg-primary",
      hoverBgContrast: "hover:bg-primary-contrast",
      hoverText: "hover:text-primary",
      hoverTextContrast: "hover:text-primary-contrast",
      hoverBorderB: "hover:border-b-primary",
    },
    "primary-contrast": {
      bg: "bg-primary-contrast",
      bgContrast: "bg-primary",
      text: "text-primary-contrast",
      textContrast: "text-primary",
      border: "border-primary-contrast",
      hoverBg: "hover:bg-primary-contrast",
      hoverBgContrast: "hover:bg-primary",
      hoverText: "hover:text-primary-contrast",
      hoverTextContrast: "hover:text-primary",
      hoverBorderB: "hover:border-b-primary-contrast",
    },
    secondary: {
      bg: "bg-secondary",
      bgContrast: "bg-secondary-contrast",
      text: "text-secondary",
      textContrast: "text-secondary-contrast",
      border: "border-secondary",
      hoverBg: "hover:bg-secondary",
      hoverBgContrast: "hover:bg-secondary-contrast",
      hoverText: "hover:text-secondary",
      hoverTextContrast: "hover:text-secondary-contrast",
      hoverBorderB: "hover:border-b-secondary",
    },
    "secondary-contrast": {
      bg: "bg-secondary-contrast",
      bgContrast: "bg-secondary",
      text: "text-secondary-contrast",
      textContrast: "text-secondary",
      border: "border-secondary-contrast",
      hoverBg: "hover:bg-secondary-contrast",
      hoverBgContrast: "hover:bg-secondary",
      hoverText: "hover:text-secondary-contrast",
      hoverTextContrast: "hover:text-secondary",
      hoverBorderB: "hover:border-b-secondary-contrast",
    },
    accent: {
      bg: "bg-accent",
      bgContrast: "bg-accent-contrast",
      text: "text-accent",
      textContrast: "text-accent-contrast",
      border: "border-accent",
      hoverBg: "hover:bg-accent",
      hoverBgContrast: "hover:bg-accent-contrast",
      hoverText: "hover:text-accent",
      hoverTextContrast: "hover:text-accent-contrast",
      hoverBorderB: "hover:border-b-accent",
    },
    "accent-contrast": {
      bg: "bg-accent-contrast",
      bgContrast: "bg-accent",
      text: "text-accent-contrast",
      textContrast: "text-accent",
      border: "border-accent-contrast",
      hoverBg: "hover:bg-accent-contrast",
      hoverBgContrast: "hover:bg-accent",
      hoverText: "hover:text-accent-contrast",
      hoverTextContrast: "hover:text-accent",
      hoverBorderB: "hover:border-b-accent-contrast",
    },
    success: {
      bg: "bg-success",
      bgContrast: "bg-success-contrast",
      text: "text-success",
      textContrast: "text-success-contrast",
      border: "border-success",
      hoverBg: "hover:bg-success",
      hoverBgContrast: "hover:bg-success-contrast",
      hoverText: "hover:text-success",
      hoverTextContrast: "hover:text-success-contrast",
      hoverBorderB: "hover:border-b-success",
    },
    "success-contrast": {
      bg: "bg-success-contrast",
      bgContrast: "bg-success",
      text: "text-success-contrast",
      textContrast: "text-success",
      border: "border-success-contrast",
      hoverBg: "hover:bg-success-contrast",
      hoverBgContrast: "hover:bg-success",
      hoverText: "hover:text-success-contrast",
      hoverTextContrast: "hover:text-success",
      hoverBorderB: "hover:border-b-success-contrast",
    },
    warning: {
      bg: "bg-warning",
      bgContrast: "bg-warning-contrast",
      text: "text-warning",
      textContrast: "text-warning-contrast",
      border: "border-warning",
      hoverBg: "hover:bg-warning",
      hoverBgContrast: "hover:bg-warning-contrast",
      hoverText: "hover:text-warning",
      hoverTextContrast: "hover:text-warning-contrast",
      hoverBorderB: "hover:border-b-warning",
    },
    "warning-contrast": {
      bg: "bg-warning-contrast",
      bgContrast: "bg-warning",
      text: "text-warning-contrast",
      textContrast: "text-warning",
      border: "border-warning-contrast",
      hoverBg: "hover:bg-warning-contrast",
      hoverBgContrast: "hover:bg-warning",
      hoverText: "hover:text-warning-contrast",
      hoverTextContrast: "hover:text-warning",
      hoverBorderB: "hover:border-b-warning-contrast",
    },
    danger: {
      bg: "bg-danger",
      bgContrast: "bg-danger-contrast",
      text: "text-danger",
      textContrast: "text-danger-contrast",
      border: "border-danger",
      hoverBg: "hover:bg-danger",
      hoverBgContrast: "hover:bg-danger-contrast",
      hoverText: "hover:text-danger",
      hoverTextContrast: "hover:text-danger-contrast",
      hoverBorderB: "hover:border-b-danger",
    },
    "danger-contrast": {
      bg: "bg-danger-contrast",
      bgContrast: "bg-danger",
      text: "text-danger-contrast",
      textContrast: "text-danger",
      border: "border-danger-contrast",
      hoverBg: "hover:bg-danger-contrast",
      hoverBgContrast: "hover:bg-danger",
      hoverText: "hover:text-danger-contrast",
      hoverTextContrast: "hover:text-danger",
      hoverBorderB: "hover:border-b-danger-contrast",
    },
    info: {
      bg: "bg-info",
      bgContrast: "bg-info-contrast",
      text: "text-info",
      textContrast: "text-info-contrast",
      border: "border-info",
      hoverBg: "hover:bg-info",
      hoverBgContrast: "hover:bg-info-contrast",
      hoverText: "hover:text-info",
      hoverTextContrast: "hover:text-info-contrast",
      hoverBorderB: "hover:border-b-info",
    },
    "info-contrast": {
      bg: "bg-info-contrast",
      bgContrast: "bg-info",
      text: "text-info-contrast",
      textContrast: "text-info",
      border: "border-info-contrast",
      hoverBg: "hover:bg-info-contrast",
      hoverBgContrast: "hover:bg-info",
      hoverText: "hover:text-info-contrast",
      hoverTextContrast: "hover:text-info",
      hoverBorderB: "hover:border-b-info-contrast",
    },
    surface: {
      bg: "bg-surface",
      bgContrast: "bg-surface-contrast",
      text: "text-surface",
      textContrast: "text-surface-contrast",
      border: "border-surface",
      hoverBg: "hover:bg-surface",
      hoverBgContrast: "hover:bg-surface-contrast",
      hoverText: "hover:text-surface",
      hoverTextContrast: "hover:text-surface-contrast",
      hoverBorderB: "hover:border-b-surface",
    },
    "surface-contrast": {
      bg: "bg-surface-contrast",
      bgContrast: "bg-surface",
      text: "text-surface-contrast",
      textContrast: "text-surface",
      border: "border-surface-contrast",
      hoverBg: "hover:bg-surface-contrast",
      hoverBgContrast: "hover:bg-surface",
      hoverText: "hover:text-surface-contrast",
      hoverTextContrast: "hover:text-surface",
      hoverBorderB: "hover:border-b-surface-contrast",
    },
    surface2: {
      bg: "bg-surface2",
      bgContrast: "bg-surface2-contrast",
      text: "text-surface2",
      textContrast: "text-surface2-contrast",
      border: "border-surface2",
      hoverBg: "hover:bg-surface2",
      hoverBgContrast: "hover:bg-surface2-contrast",
      hoverText: "hover:text-surface2",
      hoverTextContrast: "hover:text-surface2-contrast",
      hoverBorderB: "hover:border-b-surface2",
    },
    "surface2-contrast": {
      bg: "bg-surface2-contrast",
      bgContrast: "bg-surface2",
      text: "text-surface2-contrast",
      textContrast: "text-surface2",
      border: "border-surface2-contrast",
      hoverBg: "hover:bg-surface2-contrast",
      hoverBgContrast: "hover:bg-surface2",
      hoverText: "hover:text-surface2-contrast",
      hoverTextContrast: "hover:text-surface2",
      hoverBorderB: "hover:border-b-surface2-contrast",
    },
    surface3: {
      bg: "bg-surface3",
      bgContrast: "bg-surface3-contrast",
      text: "text-surface3",
      textContrast: "text-surface3-contrast",
      border: "border-surface3",
      hoverBg: "hover:bg-surface3",
      hoverBgContrast: "hover:bg-surface3-contrast",
      hoverText: "hover:text-surface3",
      hoverTextContrast: "hover:text-surface3-contrast",
      hoverBorderB: "hover:border-b-surface3",
    },
    "surface3-contrast": {
      bg: "bg-surface3-contrast",
      bgContrast: "bg-surface3",
      text: "text-surface3-contrast",
      textContrast: "text-surface3",
      border: "border-surface3-contrast",
      hoverBg: "hover:bg-surface3-contrast",
      hoverBgContrast: "hover:bg-surface3",
      hoverText: "hover:text-surface3-contrast",
      hoverTextContrast: "hover:text-surface3",
      hoverBorderB: "hover:border-b-surface3-contrast",
    },
    surface4: {
      bg: "bg-surface4",
      bgContrast: "bg-surface4-contrast",
      text: "text-surface4",
      textContrast: "text-surface4-contrast",
      border: "border-surface4",
      hoverBg: "hover:bg-surface4",
      hoverBgContrast: "hover:bg-surface4-contrast",
      hoverText: "hover:text-surface4",
      hoverTextContrast: "hover:text-surface4-contrast",
      hoverBorderB: "hover:border-b-surface4",
    },
    "surface4-contrast": {
      bg: "bg-surface4-contrast",
      bgContrast: "bg-surface4",
      text: "text-surface4-contrast",
      textContrast: "text-surface4",
      border: "border-surface4-contrast",
      hoverBg: "hover:bg-surface4-contrast",
      hoverBgContrast: "hover:bg-surface4",
      hoverText: "hover:text-surface4-contrast",
      hoverTextContrast: "hover:text-surface4",
      hoverBorderB: "hover:border-b-surface4-contrast",
    },
  };

export const TEXT_COLOR_MAP: Record<ThemeColor, { text: string }> =
  Object.fromEntries(
    (Object.keys(INTERACTIVE_COLOR_MAP) as ThemeColor[]).map((color) => [
      color,
      { text: INTERACTIVE_COLOR_MAP[color].text },
    ]),
  ) as Record<ThemeColor, { text: string }>;

export const BG_COLOR_MAP: Record<ThemeColor, string> = Object.fromEntries(
  (Object.keys(INTERACTIVE_COLOR_MAP) as ThemeColor[]).map((color) => [
    color,
    INTERACTIVE_COLOR_MAP[color].bg,
  ]),
) as Record<ThemeColor, string>;

export const BORDER_COLOR_MAP: Record<ThemeColor, string> = Object.fromEntries(
  (Object.keys(INTERACTIVE_COLOR_MAP) as ThemeColor[]).map((color) => [
    color,
    INTERACTIVE_COLOR_MAP[color].border,
  ]),
) as Record<ThemeColor, string>;